# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: "SauceCodePro Nerd Font"
    # family: "Fira Code"
    style: Regular
  bold:
    family: "SauceCodePro Nerd Font"
    style: Bold
  italic:
    family: "SauceCodePro Nerd Font"
    style: Italic
  bold_italic:
    family: "SauceCodePro Nerd Font"
    style: Bold Italic
  size: 11

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

env:
  WINIT_X11_SCALE_FACTOR: "1"
