# Font configuration
font:
  normal:
    family: "mononoki Nerd Font Mono"
    style: Regular
  bold:
    family: "mononoki Nerd Font Mono"
    style: Bold
  italic:
    family: "mononoki Nerd Font Mono"
    style: Italic
  bold_italic:
    family: "mononoki Nerd Font Mono"
    style: Bold Italic
  size: 12.5

# Gruvbox dark
colors:
  primary:
    background: "#282828"
    foreground: "#fbf1c7"
    bright_foreground: "#f9f5d7"
    dim_foreground: "#f2e5bc"

  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: CellBackground
    background: CellForeground

  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  dim:
    black: "#32302f"
    red: "#9d0006"
    green: "#79740e"
    yellow: "#b57614"
    blue: "#076678"
    magenta: "#8f3f71"
    cyan: "#427b58"
    white: "#928374"

# Environment
env:
  WINIT_X11_SCALE_FACTOR: "1"

# Options
draw_bold_text_with_bright_colors: true
